// Copyright 2017-2024 @polkadot/keyring authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev
// (packageInfo imports will be kept as-is, user-editable)

import {detectPackage} from '@polkadot/util';
import {packageInfo as cryptoInfo} from '@polkadot/util-crypto/packageInfo';
import {packageInfo as utilInfo} from '@polkadot/util/packageInfo';

import {packageInfo} from './packageInfo';

detectPackage(packageInfo, null, [cryptoInfo, utilInfo]);
